project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercise"
        menu:
          - text: "Ex 1a: Geospatial Data Science with R"
            href: hand-on-ex/hand-on-ex1/hand-on-ex1.qmd
          - text: "Ex 1b: Thematic Mapping and GeoVisualisation"
            href: hand-on-ex/hand-on-ex1/hand-on-ex1b.qmd
          - text: "---"
          - text: "Ex 2: 1st Order Spatial Point Patterns Analysis"
            href: hand-on-ex/hand-on-ex2/hand-on-ex2.qmd
          - text: "Ex 2b: 2nd Order Spatial Point Patterns Analysis"
            href: hand-on-ex/hand-on-ex2/hand-on-ex2b.qmd
      - text: "In-class Exercise"
        menu:
          - text: "Ex 1: Geospatial Data Science with R"
            href: in-class-ex/in-class-ex1/in-class-ex1.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
