{
  "hash": "a77fc1718ecd712895e245ee77025147",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class Exercise 2: Quadrat Analysis and Monte Carlo Resolution\"\nauthor: \"Ji Guofang\"\ndate: \"last-modified\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: auto\neditor: visual\n---\n\n## Overview\n\nLesson 2 covers spatial point pattern analysis in three blocks: density-based measures, distance-based measures, and the Monte Carlo machinery used to test them. [Hands-on Exercise 2](../../hand-on-ex/hand-on-ex2/hand-on-ex2.qmd) and [2b](../../hand-on-ex/hand-on-ex2/hand-on-ex2b.qmd) worked through kernel density estimation, the Clark-Evans test, and the G, F, K and L functions, and are not repeated here.\n\nTwo topics from the lecture are not touched by either hands-on exercise, and both are the subject of this in-class exercise:\n\n- **Quadrat analysis** — the density-based method the lecture presents in four steps, together with the variance-mean ratio and the weaknesses that follow from the arbitrary grid.\n- **Monte Carlo resolution** — how `nsim` sets the smallest p-value a simulation test can report and the confidence level an envelope can achieve.\n\nThe second topic answers a question the hands-on exercise raised but could not settle: why the Monte Carlo Clark-Evans test returned exactly *p* = 0.001 and no smaller.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, tmap, tidyverse)\n```\n:::\n\n\n## The Data\n\nThe same two layers as Hands-on Exercise 2.\n\n| Dataset | Source | Format |\n|----|----|----|\n| Child Care Services | [data.gov.sg](https://data.gov.sg/) | GeoJSON, point |\n| Master Plan 2019 Subzone Boundary (No Sea) | [data.gov.sg](https://data.gov.sg/) | GeoJSON, polygon |\n\n## Inputs Carried Over from Hands-on Exercise 2\n\nThe point pattern is rebuilt exactly as before — geometry only so the pattern is unmarked, jittered under a fixed seed to separate the 187 coincident locations. The reasoning is given in Hands-on Exercise 2 and is not repeated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_cl <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSea.geojson\",\n                   quiet = TRUE) %>%\n  st_transform(crs = 3414) %>%\n  filter(SUBZONE_N != \"SOUTHERN GROUP\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n\nchildcare_sf <- st_read(\"data/geospatial/ChildCareServices.geojson\",\n                        quiet = TRUE) %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 3414)\n\nset.seed(1234)\nchildcare_ppp <- rjitter(as.ppp(st_geometry(childcare_sf)),\n                         retry = TRUE, nsim = 1, drop = TRUE)\n\nchildcareSG_ppp <- childcare_ppp[as.owin(mpsz_cl)]\nchildcare_ck_ppp <- childcare_ppp[as.owin(filter(mpsz_cl, PLN_AREA_N == \"CHOA CHU KANG\"))]\n\nc(Singapore = npoints(childcareSG_ppp),\n  `Choa Chu Kang` = npoints(childcare_ck_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Singapore Choa Chu Kang \n         1925            74 \n```\n\n\n:::\n:::\n\n\n## Quadrat Analysis\n\nThe lecture sets out quadrat analysis in four steps: divide the study area into subregions of equal size, count the events in each, calculate the intensity of each, then compute a quadrat statistic and test it against CSR.\n\n### Step 1 and 2: Dividing the area and counting events\n\n`quadratcount()` performs both steps at once. `nx` and `ny` set the number of columns and rows in the grid:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqc_sg <- quadratcount(childcareSG_ppp, nx = 6, ny = 4)\nqc_sg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntile\nTile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 1, col 4 \n                0                 0               247                33 \nTile row 1, col 5 Tile row 2, col 1 Tile row 2, col 2 Tile row 2, col 3 \n                0                 0               226               114 \nTile row 2, col 4 Tile row 2, col 5 Tile row 2, col 6 Tile row 3, col 1 \n              371               166                 0                 0 \nTile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 Tile row 3, col 5 \n               99               256               307                82 \nTile row 3, col 6 Tile row 4, col 1 Tile row 4, col 2 Tile row 4, col 3 \n                0                 0                 0                24 \nTile row 4, col 4 \n                0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(childcareSG_ppp, cex = 0.4, pch = 16,\n     main = \"Childcare centres with a 6 x 4 quadrat grid\")\nplot(qc_sg, add = TRUE, col = \"firebrick\", cex = 1.2)\n```\n\n::: {.cell-output-display}\n![](in-class-ex2_files/figure-html/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\nNote that the 6 × 4 grid does not produce 24 quadrats. The observation window is the Singapore coastline, not a rectangle, so cells falling entirely in the sea are dropped and the ones along the coast are clipped to irregular shapes. Several of the surviving tiles hold no centres at all.\n\n### Step 3: Intensity per quadrat\n\nCounts are not comparable between tiles once the window has clipped them to different areas. `intensity()` divides each count by its tile's area — the values below are centres per square kilometre:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(intensity(qc_sg) * 1000000, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntile\nTile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 1, col 4 \n            0.000             0.000             4.447             1.328 \nTile row 1, col 5 Tile row 2, col 1 Tile row 2, col 2 Tile row 2, col 3 \n            0.000             0.000             3.534             1.783 \nTile row 2, col 4 Tile row 2, col 5 Tile row 2, col 6 Tile row 3, col 1 \n            5.802             3.420             0.000             0.000 \nTile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 Tile row 3, col 5 \n            2.423             4.044             5.897             2.877 \nTile row 3, col 6 Tile row 4, col 1 Tile row 4, col 2 Tile row 4, col 3 \n            0.000             0.000             0.000             1.607 \nTile row 4, col 4 \n            0.000 \n```\n\n\n:::\n:::\n\n\n### Step 4: The quadrat statistic and the CSR test\n\n`quadrat.test()` compares the observed counts against the counts expected if the pattern were CSR, using a Pearson chi-squared statistic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt_sg <- quadrat.test(childcareSG_ppp, nx = 6, ny = 4)\nqt_sg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test of CSR using quadrat counts\n\ndata:  childcareSG_ppp\nX2 = 935.42, df = 20, p-value < 2.2e-16\nalternative hypothesis: two.sided\n\nQuadrats: 21 tiles (irregular windows)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(childcareSG_ppp, cex = 0.4, pch = 16, main = \"Observed / expected / residual\")\nplot(qt_sg, add = TRUE, cex = 0.8, col = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![](in-class-ex2_files/figure-html/unnamed-chunk-7-1.png){width=864}\n:::\n:::\n\n\nEach tile now carries three numbers: observed count, expected count under CSR, and the Pearson residual. The residuals are what the chi-squared statistic sums.\n\n::: callout-warning\n## The test warns about itself\n\nThe output carries the note *\"Some expected counts are small; chi^2 approximation may be inaccurate\"*. The chi-squared distribution is an approximation that requires a reasonable expected count in every cell, and the clipped coastal tiles violate that. The simulated version in the second half of this exercise avoids the assumption entirely, which is one practical reason to prefer it.\n:::\n\n### The variance-mean ratio\n\nThe lecture gives the VMR as the summary of what the quadrat counts say about the pattern: **close to 0** for a uniform distribution, **close to 1** for a random one, and **greater than 1** for a clustered one. The logic is that a Poisson process has variance equal to its mean, so any excess variance is clustering.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts_sg <- as.vector(qc_sg)\n\nc(mean = mean(counts_sg),\n  variance = var(counts_sg),\n  VMR = var(counts_sg) / mean(counts_sg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       mean    variance         VMR \n   91.66667 14589.73333   159.16073 \n```\n\n\n:::\n:::\n\n\nA VMR far above 1 says the counts vary between tiles much more than a random process would produce — the pattern is clustered.\n\n### The weakness: sensitivity to quadrat size\n\nThe lecture lists three weaknesses of quadrat analysis, and the first is that it is sensitive to the quadrat size. Repeating the whole procedure across a range of grids makes the size of that effect concrete:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid_sizes <- c(2, 4, 6, 8, 10, 14)\n\nquadrat_summary <- map_dfr(grid_sizes, function(n) {\n  qc <- quadratcount(childcareSG_ppp, nx = n, ny = n)\n  v <- as.vector(qc)\n  tt <- suppressWarnings(quadrat.test(childcareSG_ppp, nx = n, ny = n))\n  tibble(grid = paste0(n, \" x \", n),\n         tiles = length(v),\n         mean = mean(v),\n         variance = var(v),\n         VMR = var(v) / mean(v),\n         X2 = as.numeric(tt$statistic),\n         p = tt$p.value)\n})\n\nquadrat_summary %>%\n  mutate(across(c(mean, variance, VMR, X2), ~ round(.x, 2)),\n         p = format.pval(p, digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  grid    tiles  mean variance   VMR    X2 p     \n  <chr>   <int> <dbl>    <dbl> <dbl> <dbl> <chr> \n1 2 x 2       4 481.    12675.  26.3  183. <2e-16\n2 4 x 4      14 138.    31371. 228.   964. <2e-16\n3 6 x 6      29  66.4    7555. 114.  1064. <2e-16\n4 8 x 8      46  41.8    2980.  71.2 1354. <2e-16\n5 10 x 10    67  28.7    1255.  43.7 1389. <2e-16\n6 14 x 14   120  16.0     503.  31.3 2144. <2e-16\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Interpretation\n\nThe VMR ranges from about 26 to about 228 across these six grids. That is a ninefold swing produced by nothing but the choice of grid, on one unchanged point pattern — so the VMR cannot be read as a property of the pattern, only as a property of the pattern *and* the grid used to measure it.\n\nThe direction of the answer is stable: every grid rejects CSR, and every VMR is far above 1, so the conclusion that childcare centres are clustered does not depend on the choice. The magnitude is not stable at all, which is why a VMR should never be quoted without the grid that produced it.\n\nThe 4 × 4 grid gives the extreme value because its cells are large enough to straddle both the dense central corridor and the empty catchment, maximising the variance between tiles. Finer grids break those contrasts up into more, smaller cells and the ratio falls.\n:::\n\nThe lecture's other two weaknesses are visible in the same table. Quadrat analysis is a measure of **dispersion** rather than of pattern: it counts how uneven the tiles are, but rearranging the centres within a tile changes nothing. And it returns **a single number for the whole region**, so it cannot say that Tampines is clustered while Choa Chu Kang is not — a distinction the Clark-Evans tests in Hands-on Exercise 2 did make.\n\n## Monte Carlo Resolution\n\nThe lecture's closing block concerns how `nsim` governs what a simulation test can report. Two consequences follow, and both can be demonstrated directly.\n\n### How nsim sets the smallest reportable p-value\n\nA Monte Carlo p-value is a rank, not a continuous quantity. The observed statistic is placed among `nsim` simulated ones, so the p-value can only take the values 1/(nsim+1), 2/(nsim+1), and so on. The lecture states the consequence: with `nsim = 99` the smallest p-value obtainable is 0.01, and with `nsim = 999` it is 0.001.\n\nRunning the simulated quadrat test on the strongly clustered national pattern at three simulation counts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dfr(c(19, 99, 999), function(n) {\n  set.seed(1234)\n  tt <- suppressWarnings(\n    quadrat.test(childcareSG_ppp, nx = 6, ny = 4,\n                 method = \"MonteCarlo\", nsim = n))\n  tibble(nsim = n,\n         p_two_sided = tt$p.value,\n         floor_1 = 1 / (n + 1),\n         floor_2 = 2 / (n + 1))\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n   nsim p_two_sided floor_1 floor_2\n  <dbl>       <dbl>   <dbl>   <dbl>\n1    19       0.1     0.05    0.1  \n2    99       0.02    0.01    0.02 \n3   999       0.002   0.001   0.002\n```\n\n\n:::\n:::\n\n\nEvery p-value equals **2/(nsim+1)**, not the 1/(nsim+1) the lecture quotes. The reason is that `quadrat.test()` defaults to `alternative = \"two.sided\"`, which spends half the probability in each tail. Asking a directional question restores the lecture's floor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dfr(c(19, 99, 999), function(n) {\n  set.seed(1234)\n  tt <- suppressWarnings(\n    quadrat.test(childcareSG_ppp, nx = 6, ny = 4,\n                 method = \"MonteCarlo\", nsim = n,\n                 alternative = \"clustered\"))\n  tibble(nsim = n,\n         p_one_sided = tt$p.value,\n         floor_1 = 1 / (n + 1))\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n   nsim p_one_sided floor_1\n  <dbl>       <dbl>   <dbl>\n1    19       0.05    0.05 \n2    99       0.01    0.01 \n3   999       0.001   0.001\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## This explains the Clark-Evans result\n\nHands-on Exercise 2 ran `clarkevans.test()` with `method = \"MonteCarlo\"`, `nsim = 999` and `alternative = \"clustered\"`, and got exactly *p* = 0.001. That is the one-sided floor, 1/(999+1): not one of the 999 simulated CSR patterns produced an *R* as extreme as the observed 0.552.\n\nThe practical point is that such a p-value should be read as \"*p* ≤ 0.001, based on 999 simulations\" rather than as a measured value. Reporting it as though it were an ordinary p-value overstates what the test resolved, and comparing it against an asymptotic p-value such as 2.2e-16 compares two different things.\n:::\n\n### How nsim sets the achievable confidence level\n\nThe lecture makes a second point about `envelope()`: the confidence level is constrained by `nsim`, and with `nsim = 99` the finest two-tailed envelope is at 98% confidence.\n\nBy default `envelope()` shades the region between the pointwise **minimum and maximum** of the simulations. Discarding exactly one value in each tail leaves a confidence level of 1 − 2/(nsim+1):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenvelope_summary <- map_dfr(c(19, 99, 999), function(n) {\n  set.seed(1234)\n  e <- envelope(childcare_ck_ppp, Gest, nsim = n, verbose = FALSE)\n  tibble(nsim = n,\n         confidence = paste0(round(100 * (1 - 2 / (n + 1)), 1), \"%\"),\n         mean_width = round(mean(e$hi - e$lo, na.rm = TRUE), 4))\n})\n\nenvelope_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n   nsim confidence mean_width\n  <dbl> <chr>           <dbl>\n1    19 90%             0.129\n2    99 98%             0.202\n3   999 99.8%           0.265\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3))\nfor (n in c(19, 99, 999)) {\n  set.seed(1234)\n  plot(envelope(childcare_ck_ppp, Gest, nsim = n, verbose = FALSE),\n       main = paste0(\"nsim = \", n))\n}\n```\n\n::: {.cell-output-display}\n![](in-class-ex2_files/figure-html/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\n## Interpretation\n\nThe envelope gets **wider** as `nsim` increases — mean width 0.129, 0.202, 0.265 — which is the opposite of the usual intuition that more simulations mean more precision.\n\nThere is no contradiction. A default envelope is the minimum and maximum of the simulations, and the extremes of 999 draws are further apart than the extremes of 19. What rises with `nsim` is the confidence level: 90.0%, then 98.0%, then 99.8%. A wider band at higher confidence is not a less precise result, it is a different statement.\n\nThe consequence for reading these plots is that a curve escaping a 19-simulation envelope is weak evidence, while the same curve escaping a 999-simulation envelope is strong. The two pictures are not interchangeable, and an envelope plot is uninterpretable unless the `nsim` behind it is stated.\n\nTo hold the confidence level fixed while increasing `nsim`, `nrank` has to rise with it — `nrank = 25` with `nsim = 999` gives the same 95% level as `nrank = 1` with `nsim = 39`.\n:::\n\n### Rule of thumb\n\nThe lecture's practical guidance, confirmed by the results above:\n\n- Use at least `nsim = 99` for quick exploratory tests, and `nsim = 999` or more for stable p-values and smooth envelopes.\n- Report p-values together with their Monte Carlo resolution — \"*p* < 0.001, based on 999 simulations\" — rather than as bare numbers.\n- State `nsim` alongside every envelope plot, since the same curve carries different weight at different simulation counts.\n\n## Reference\n\n- Kam, T. S. *ISSS626 Geospatial Analytics and Applications*, Lesson 2 — Spatial Point Patterns Analysis.\n- [Chapter 11 Point Pattern Analysis](https://mgimond.github.io/Spatial/point-pattern-analysis.html) of *Intro to GIS and Spatial Analysis*, sections 11.2–11.4.\n- [Chapter 12 Hypothesis testing](https://mgimond.github.io/Spatial/hypothesis-testing.html) of the same text.\n- Baddeley, A., Rubak, E. and Turner, R. (2015) *Spatial Point Patterns: Methodology and Applications with R*. Chapman and Hall/CRC.\n",
    "supporting": [
      "in-class-ex2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}